CREATE TABLE IF NOT EXISTS weekly_stats (

  week TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  spent INTEGER NOT NULL DEFAULT 0,
  revenue INTEGER NOT NULL DEFAULT 0,
  single_count INTEGER NOT NULL DEFAULT 0,
  bulk_count INTEGER NOT NULL DEFAULT 0,
  donations INTEGER NOT NULL DEFAULT 0
  
);
