name = "prchsalerts" 
main = "index.js" 
compatibility_date = "2025-06-07" 

[observability] 
enabled = false 
head_sampling_rate = 1 

[observability.logs] 
enabled = true 
head_sampling_rate = 1 
persist = true 
invocation_logs = true 

[observability.traces] 
enabled = true 
persist = true 
head_sampling_rate = 1 

[[kv_namespaces]] 
binding = "WEEKLY_STATS" 
id = "420ea278f9c0497dbf84832983d4881b" 

[triggers] 
crons = ["0 6 * * 1"]
